# Generated by Django 5.2.4 on 2025-07-31 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysocial', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(default='photos/default.png', upload_to='photos/'),
        ),
    ]
