# Generated by Django 5.2.4 on 2025-08-06 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='chage_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_photo', models.ImageField(upload_to='profile/')),
                ('caption', models.TextField(max_length=600)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profileapp.userprofile')),
            ],
        ),
    ]
