# Generated by Django 5.2.4 on 2025-08-06 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0002_chage_profile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='chage_profile',
            new_name='ChageProfile',
        ),
    ]
